version: '3'

tasks:
  abc:
    dir: '{{.USER_WORKING_DIR}}/ABC'
    cmds:
      - cargo compete new {{.CLI_ARGS}} && cargo member include {{.CLI_ARGS}}

  abc-test-a:
    dir: '{{.USER_WORKING_DIR}}/ABC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete test a --release

  abc-test-b:
    dir: '{{.USER_WORKING_DIR}}/ABC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete test b

  abc-test-c:
    dir: '{{.USER_WORKING_DIR}}/ABC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete test c

  abc-test-d:
    dir: '{{.USER_WORKING_DIR}}/ABC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete test d

  abc-submit-a:
    dir: '{{.USER_WORKING_DIR}}/ABC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete submit a --release

  abc-submit-b:
    dir: '{{.USER_WORKING_DIR}}/ABC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete submit b --release

  abc-submit-c:
    dir: '{{.USER_WORKING_DIR}}/ABC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete submit c --release

  abc-submit-d:
    dir: '{{.USER_WORKING_DIR}}/ABC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete submit d --release

  arc:
    dir: '{{.USER_WORKING_DIR}}/ARC'
    cmds:
      - cargo compete new {{.CLI_ARGS}} && cargo member include {{.CLI_ARGS}}

  arc-test-a:
    dir: '{{.USER_WORKING_DIR}}/ARC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete test a --release

  arc-test-b:
    dir: '{{.USER_WORKING_DIR}}/ARC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete test b --release

  arc-test-c:
    dir: '{{.USER_WORKING_DIR}}/ARC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete test c --release

  arc-test-d:
    dir: '{{.USER_WORKING_DIR}}/ARC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete test d --release

  arc-submit-a:
    dir: '{{.USER_WORKING_DIR}}/ARC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete submit a --release

  arc-submit-b:
    dir: '{{.USER_WORKING_DIR}}/ARC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete submit b --release

  arc-submit-c:
    dir: '{{.USER_WORKING_DIR}}/ARC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete submit c --release

  arc-submit-d:
    dir: '{{.USER_WORKING_DIR}}/ARC/{{.CLI_ARGS}}'
    cmds:
      - cargo compete submit d --release
